artifacts_root : 'artifacts'
models_root : 'models'

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: 'https://github.com/AnkitSangode/JavaScriptMiniProjects/raw/refs/heads/main/UpdatedResumeDataSet.csv'
  local_data_file: artifacts/data_ingestion/UpdatedResumeDataSet.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/UpdatedResumeDataSet.csv

feature_engineering:
  root_dir: artifacts/feature_engineering
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv


model_trainer:
  root_dir: artifacts/model_trainer
  X_train_path: artifacts/feature_engineering/X_train_tfidf.pkl
  y_train_path: artifacts/feature_engineering/y_train_ml.npy
  X_test_path: artifacts/feature_engineering/X_test_tfidf.pkl
  y_test_path: artifacts/feature_engineering/y_test_ml.npy

deep_model_trainer:
  root_dir: artifacts/deep_model_trainer
  X_train_path: artifacts/feature_engineering/X_train_pad.npy
  y_train_path: artifacts/feature_engineering/y_train_dl.npy
  X_test_path: artifacts/feature_engineering/X_test_pad.npy
  y_test_path: artifacts/feature_engineering/y_test_dl.npy

model_evaluation:
  test_data_path: artifacts/data_transformation/test.csv
  label_encoder_path: artifacts/feature_engineering/labelEncoder.pkl
  vectorizer_path: artifacts/feature_engineering/vectorizer.pkl
  ml_model_path:
    logreg: artifacts/model_trainer/logisticregression.pkl
    rf: artifacts/model_trainer/randomforestclassifier.pkl
    svc: artifacts/model_trainer/svm.pkl
  dl_model_path: artifacts/deep_model_trainer/deep_model.h5

