artifacts_root : 'artifacts'
models_root : 'models'

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: 'https://github.com/AnkitSangode/JavaScriptMiniProjects/raw/refs/heads/main/UpdatedResumeDataSet.csv'
  local_data_file: artifacts/data_ingestion/UpdatedResumeDataSet.csv

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/UpdatedResumeDataSet.csv